matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          language: c
        - os: osx
          language: c
          osx_image: xcode7.3

cache:
  directories:
  - dependencies/linux
  - dependencies/osx

before_install:
  - date +%s > ${HOME}/start_time
  - ls -lh "dependencies/${TRAVIS_OS_NAME}"
  - du -h -d 2 dependencies

install:
  - ./reproducible_build.sh -t -o -d

script:
  - ./reproducible_build.sh -t -o -l

before_cache:
  - rm -rf dependencies/${TRAVIS_OS_NAME}/boost_1_59_0 dependencies/${TRAVIS_OS_NAME}/db-4.8.30.NC dependencies/${TRAVIS_OS_NAME}/libevent dependencies/${TRAVIS_OS_NAME}/openssl-1.0.1p dependencies/${TRAVIS_OS_NAME}/*.tar.* atomic.patch
  - du -h -d 2 dependencies
